# Generated by Django 5.0.2 on 2024-02-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
